config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments, :only => [:create, :destroy]
  get 'profile', as: 'user_root', controller: 'users'
  devise_for :users
  root to: 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment_hash = params[:comment]
    @obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
    # Not implemented: check to see whether the user has permission to create a comment on this object
    @comment = Comment.build_from(@obj, current_user.id, @comment_hash[:body])
    if @comment.save
      render :partial => 'comments/comment', :locals => { :comment => @comment }, :layout => false, :status => :created
    else
      render :js => 'alert("error saving comment");'
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :json => @comment, :status => :ok
    else
      render :js => "alert('error deleting comment');"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to posts_path if user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comment_threads.order('created_at desc')
    @new_comment = Comment.build_from(@post, current_user.id, '')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @posts = Post.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.slim
.comment id=('comment-#{comment.id}')
  hr
  = link_to '×', comment_path(comment), :method => :delete, :remote => true, \
          :confirm => 'Are you sure you want to remove this comment?', :disable_with => '×', :class => 'close' \
          if comment.user_id == current_user.id
  h4
    =' User.find(comment.user_id).email
    small= comment.updated_at
  p= comment.body

app/views/comments/_form.html.slim
.comment-form
  = simple_form_for comment, :remote => true do |f|
    = f.input :body, :input_html => { :rows => '2' }, :label => false
    = f.input :commentable_id, :as => :hidden, :value => comment.commentable_id
    = f.input :commentable_type, :as => :hidden, :value => comment.commentable_type
    = f.button :submit, :class => 'btn btn-primary', :disable_with => 'Submitting…'

app/views/home/index.html.slim
.margin70.container
  header
    .header-content
      .header-content-inner
        h1.text-center BlogApp on Ruby on Rails
        hr
        .text-center
          p Register now and you can create own posts and comment other posts!
          a.btn.btn-primary.btn-xl href='/users/sign_up'  Join us

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=('text/html; charset=UTF-8') http-equiv="Content-Type" /
    title BlogApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" /
    link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css" /
  body
    nav#mainNav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand.page-scroll href='/'  Blog App
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                a.page-scroll href="/posts"  All posts
              li
                a.page-scroll href="/profile"  My posts
              li
                = link_to 'Create', new_post_path
              li
                = link_to 'Logout', destroy_user_session_path, :method => :delete
            - else
              li
                a.page-scroll href="/users/sign_in" Sign in
    = yield

app/views/posts/_form.html.slim
= form_for @post, html: { class: 'form form-horizontal post' } do |f|
  .form-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'form-control'
    = error_span(@post[:title])
  .form-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_area :body, :class => 'form-control'
    = error_span(@post[:body])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t('helpers.links.cancel')), posts_path, :class => 'btn'

app/views/posts/edit.html.slim
- model_class = Post
.page-header.col-lg-6.col-lg-offset-3
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
  = render :partial => 'form'

app/views/posts/index.html.slim
.row.margin70
  .col-lg-8.col-lg-offset-2
    h4 = t '.title', :default => 'Posts'
    - @posts.each do |post|
      .panel.panel-default
        .panel-heading
          .text-center
            .row
              .col-lg-9
                h4.pull-left = link_to post.title, post_path(post)
              .col-lg-3
                h4.pull-right
                  = link_to t('.edit', :default => t('.helpers.links.edit')), edit_post_path(post), :class => 'btn btn-info btn-sm pull-right' if post.user_id == current_user.id
        .panel-body
          p = post.body
        .panel-footer.clearfix
          span
            =' post.created_at.strftime('%d-%b-%y %H:%M')
          span
            =' link_to t('.destroy', :default => t('.helpers.links.destroy')), post_path(post), :method => :delete, :data => {:confirm => t('.confirm', :default => t('.helpers.links.confirm ', :default => 'Are you sure?'))}, :class => 'btn btn-danger pull-right btn-sm' if post.user_id == current_user.id

app/views/posts/new.html.slim
- model_class = Post
.page-header.col-lg-6.col-lg-offset-3
  h1 = t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
  = render :partial => 'form'

app/views/posts/show.html.slim
.page-header.col-lg-8.col-lg-offset-2
  h1 = 'Post'
  .panel.panel-default
    .panel-heading
      h4= @post.title
    .panel-body
      p= @post.body
  .pull-right
    = link_to t('.back', :default => t('helpers.links.back')), posts_path, :class => 'btn btn-default'
    '
    = link_to t('.edit', :default => t('helpers.links.edit')), edit_post_path(@post), :class => 'btn btn-default' if @post.user_id == current_user.id
    '
    = link_to t('.destroy', :default => t('helpers.links.destroy')), post_path(@post), :method => 'delete', :data => { :confirm => t('.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) }, :class => 'btn btn-danger' if @post.user_id == current_user.id
  h2 Comments
  = render :partial => 'comments/form', :locals => { :comment => @new_comment }
  = render :partial => 'comments/comment', :collection => @comments, :as => :comment

app/views/users/profile.html.slim
.row.margin70
  .col-lg-8.col-lg-offset-2
    h4 = t '.title', :default => 'My posts (' + current_user.email + ')'
    - if @posts.empty?
      hr
      p.text-center You haven't posts yet
    -else
      - @posts.each do |post|
        .panel.panel-default
          .panel-heading
            .text-center
              .row
                .col-lg-9
                  h4.pull-left = link_to post.title, post_path(post)
                .col-lg-3
                  h4.pull-right
                    = link_to t('.edit', :default => t('.helpers.links.edit')), edit_post_path(post), :class => 'btn btn-info btn-sm pull-right'
          .panel-body
            p = post.body
          .panel-footer.clearfix
            span
              =' post.created_at.strftime('%d-%b-%y %H:%M')
            span
              =' link_to t('.destroy', :default => t('.helpers.links.destroy')), post_path(post), :method => :delete, :data => {:confirm => t('.confirm', :default => t('.helpers.links.confirm ', :default => 'Are you sure?'))}, :class => 'btn btn-danger pull-right btn-sm'